services:
  willinn-users-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    container_name: willinn-Users-db
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - users-data:/var/opt/mssql

volumes:
  users-data: {}
   